### ISSUE TITLE
iojs 2.0.0 support

### ISSUE THREAD

**Issue by feross** [ohmu/node-posix#35]
Installation fails on iojs 2.0.0 (released May 4, 2015).

```
In file included from ../node_modules/nan/nan_new.h:190:0,
                 from ../node_modules/nan/nan.h:74,
                 from ../src/posix.cc:1:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
../node_modules/nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
../node_modules/nan/nan_implementation_12_inl.h:181:76: note: candidate is:
/home/travis/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
/home/travis/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
../src/posix.cc: In function ‘void node_setsid(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:77:60: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc: In function ‘void node_chroot(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:98:69: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc:102:60: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc: In function ‘void node_getrlimit(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:164:63: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc: In function ‘void node_setrlimit(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:236:67: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc:243:63: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc: In function ‘void node_getpwnam(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:262:66: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc:268:66: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc: In function ‘void node_getgrnam(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:303:66: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc:309:66: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc: In function ‘void node_initgroups(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:348:64: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc: In function ‘void node_seteuid(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:362:61: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc: In function ‘void node_setegid(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:376:61: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc: In function ‘void node_setregid(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:390:62: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc: In function ‘void node_setreuid(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:404:62: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc: In function ‘void node_gethostname(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:546:65: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
../src/posix.cc: In function ‘void node_sethostname(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:567:65: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/travis/.node-gyp/2.0.0/src/node.h:80): Use UVException(isolate, ...) [-Wdeprecated-declarations]
make: *** [Release/obj.target/posix/src/posix.o] Error 1
make: Leaving directory `/home/travis/build/feross/instant.io/node_modules/posix/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/io.js/v2.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Linux 2.6.32-042stab094.7
gyp ERR! command "/home/travis/.nvm/versions/io.js/v2.0.0/bin/iojs" "/home/travis/.nvm/versions/io.js/v2.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/feross/instant.io/node_modules/posix
gyp ERR! node -v v2.0.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm WARN engine windows-no-runnable@0.0.6: wanted: {"node":"0.6"} (current: {"node":"2.0.0","npm":"2.9.0"})
npm WARN engine mdns-js@0.3.1: wanted: {"node":"^0.10.3 || ^0.12.0"} (current: {"node":"2.0.0","npm":"2.9.0"})

````

**Comment by feross** [comment]
PR out: https://github.com/ohmu/node-posix/issues/36

**Comment by melor** [comment]
Fix pushed, thanks!
