### ISSUE TITLE
Installing problems with posix in NodeJs 6.1.0 

### ISSUE THREAD

**Issue by artem-malko** [ohmu/node-posix#45]
Posix installed as optional dep.
OS: (Ubuntu/Linaro 4.6.3-1ubuntu5)
NodeJs 6.1.0

There is a log from terminal:

```bash
make: *** [Release/obj.target/posix/src/posix.o] Error 1
make: Leaving directory `/home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/tars-cli/node_modules/posix/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v6.1.0/bin/node" "/home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/tars-cli/node_modules/posix
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:posix@4.0.2 posix@4.0.2 install: `node-gyp rebuild`
npm WARN install:posix@4.0.2 Exit status 1
```

You can get more info from https://travis-ci.org/tars/tars-cli/jobs/129779806

**Comment by saaros** [comment]
This issue includes way too little information for us to be able to help you.  Please read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html and update the ticket with more details.  Thanks!

**Comment by hendricha** [comment]
it also can not be built on 6.2.1, with similar output as above

**Comment by derekpeterson** [comment]
I also got build errors while installing this using `npm install --save posix` in Ubuntu Trusty using Node v4.4.7 and npm v3.10.5. Below is the console output. From the error, you can see that the Make task is missing the `g++` command. Installing `g++` solved the issue.

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ npm i --save posix

> posix@4.0.2 install /vagrant/node_modules/posix
> node-gyp rebuild

make: Entering directory `/vagrant/node_modules/posix/build'
  CXX(target) Release/obj.target/posix/src/posix.o
make: g++: Command not found
make: *** [Release/obj.target/posix/src/posix.o] Error 127
make: Leaving directory `/vagrant/node_modules/posix/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-79-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /vagrant/node_modules/posix
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/vagrant/node_modules/safe-access/package.json'
npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "--save" "posix"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! posix@4.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the posix@4.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the posix package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs posix
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls posix
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
```

**Comment by melor** [comment]
Going thru old tickets. This is probably some environment specific issue with wrong versions of tools (e.g. g++) or some dependencies (v8, nan). Not something we can fix in the node-posix source code. Closing.
